name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
        working-directory: backend

  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: build_backend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
        
      - name: Build frontend
        run: npm run build
        working-directory: frontend

  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: build_frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: maven
      
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS todo_db;' -uroot -proot
          mysql -e 'CREATE USER IF NOT EXISTS "user"@"localhost" IDENTIFIED BY "password";' -uroot -proot
          mysql -e 'GRANT ALL PRIVILEGES ON todo_db.* TO "user"@"localhost";' -uroot -proot
          mysql -e 'FLUSH PRIVILEGES;' -uroot -proot
      
      - name: Run tests
        run: mvn test
        working-directory: backend
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/todo_db
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password